# Kubernetes delegates writable cgroup feature to CRI.
# github issue: https://github.com/kubernetes/kubernetes/issues/121190
#
# Depending on different CRI implementations, there're writable cgroup supported or ongoing.
# cri-o PR: https://github.com/cri-o/cri-o/pull/5277
# containerd PR: https://github.com/containerd/containerd/pull/11131
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stall-forever
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stall-forever
  template:
    metadata:
      labels:
        app: stall-forever
    spec:
      containers:
      - name: stall-forever
        image: dentiny:stall_image
        # Processes in privileged containers are essentially equivalent to root on the host.
        # Reference: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.32/#securitycontext-v1-core
        securityContext:
          privileged: true
        ports:
        - containerPort: 8080
