# github issue: https://github.com/kubernetes/kubernetes/issues/121190
# cri PR: https://github.com/cri-o/cri-o/pull/5277
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stall-forever
  # TODO(hjiang): Certain annotation doesn't work.
  annotations:
    io.kubernetes.cri-o.cgroup2-mount-hierarchy-rw: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stall-forever
  template:
    metadata:
      labels:
        app: stall-forever
    spec:
      containers:
      - name: stall-forever
        image: dentiny:stall_image
        # Processes in privileged containers are essentially equivalent to root on the host.
        # Reference: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.32/#securitycontext-v1-core
        securityContext:
          privileged: true
          # TODO(hjiang): Certain capability doesn't work.
          capabilities:
            add:
            - SYS_RESOURCE
        ports:
        - containerPort: 8080
