# github issue:
# - https://github.com/kubernetes/kubernetes/issues/121190
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stall-forever
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stall-forever
  template:
    metadata:
      labels:
        app: stall-forever
      annotations:
        io.kubernetes.cri-o.cgroup2-mount-hierarchy-rw: "true"
    spec:
      containers:
      - name: stall-forever
        image: dentiny:stall_image
        # Processes in privileged containers are essentially equivalent to root on the host.
        # Reference: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.32/#securitycontext-v1-core
        securityContext:
          privileged: true
        ports:
        - containerPort: 8080
